#!/usr/bin/env ruby
# Run the Biomine Object Exchance server.
# Usage: ./run_bmoe_server [listen_ip:port|port] [linked_server:port ...]

$LOAD_PATH << '.' unless $LOAD_PATH.include? '.'
require 'bmoe_server'

DEFAULT_PORT = 7890

def ip_and_port_from_arg(arg)
  fields = arg.split(':')
  if fields.size >= 2
    port = fields.pop.to_i
    address = fields.join(':')
    return address, port
  end
  return '0.0.0.0', arg.to_i
end

EventMachine.epoll
EventMachine.run do
  server = BiomineOE::Server.new
  ip, port = ip_and_port_from_arg(ARGV.shift || DEFAULT_PORT.to_s)
  server.start(ip, port)
  ARGV.each do |arg|
    ip, port = ip_and_port_from_arg(arg)
    server.connect_to_server(ip, port)
  end
end
