#!/usr/bin/env ruby
$LOAD_PATH << '.' unless $LOAD_PATH.include? '.'
require 'bmoe_client'

server, port = (ARGV[0] || '127.0.0.1:7890'), ARGV[1].to_i

if port <= 0
  fields = server.split(':')
  if fields.size >= 2
    port = fields.pop.to_i
    server = fields.join(':')
  end
end

EventMachine.run do
  c = EventMachine.connect(server, port, BiomineOE::ClientConnection)
  if c
    EventMachine.open_keyboard(BiomineOE::KeyboardInput, c)
  else
    EventMachine.stop
  end
end
